### ISSUE TITLE
BinMod can't run on windows server

### ISSUE THREAD

**Issue by realyigo** [AutoHotkey/Ahk2Exe#111]
BinMod works fine on Win10, but can't run on windows server.
I tried windows 2012, 2019, 2022,  virutal machine, physical server.    All fails.
It seems something wrong in function InBuf

**Comment by TAC109** [comment]
Sorry you are having problems. Could you give some more information on what is failing please. For example, any error messages, a sample script that is failing, anything else that is relevant.

Thanks

**Comment by realyigo** [comment]
In the SimpleScript.zip, there is a script called tmp.ahk, which use ScriptGuard.
I can compile it using Ahk2Exe.exe on Win10 64bit.
But on windows server 64bit. I got below error
-----------------------------------------
Error: String not found!
#1=1;">AUTOHOTKEY SCRIPT<"
----------------------------------------
The error message is not right. The root cause was InBuf throws exceptions  0xc0000005, but the program take it as string not found.

The ScriptGuard is amazing, It helps me a lot. Thank you very much.
I wrote a bat on the windows server to do a daily build. But I got above error.

[SimpleScript.zip](https://github.com/user-attachments/files/19100270/SimpleScript.zip)

**Comment by TAC109** [comment]
Thanks for the information, which has helped me find the source of the problem. I have attached an amended BinMod.exe which should fix the issue. I have regression-tested this successfully on my Windows 10 system. As I don't have a server for a final test I would appreciate if you could do this for me and let me know the outcome.

Cheers

[BinMod.zip](https://github.com/user-attachments/files/19115902/BinMod.zip)

**Comment by realyigo** [comment]
new BinMod still failed on windows server. I tested it on win2012 64bit physical server, win2022 64bit virutal machine.
I can't find private chat function on Github.
Can you give me your email? I can provide a windows server.
Thank you very much

**Comment by realyigo** [comment]
I have email the username/password to you.
My email is realyigo@gmail.com
I don't know what vm software it is. I think vm is no matter with the error, cause it also failed on physical server

**Comment by TAC109** [comment]
I have issued a new version of BinMod which will fix the issue you were having. It appears that Windows server editions are issued with DEP set to 'all programs' whereas other editions have DEP set to 'essential Windows programs and services only'. (DEP = Data Execution Prevention).

You can download the new version using the Ahk2Exe menu 'Help' -> 'Check for updates'.

Thank you for your help with resolving this problem.
